name: practical_machine_learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - scipy
  - matplotlib
  - pandas
  - notebook
  - plotly
  - mlflow
  - seaborn
  - scikit-learn